### ISSUE TITLE
Agregar Carpeta Scripts a Resources

### ISSUE THREAD

**Issue by alanrodas** [glmaljkovich/aterrizar.com#1]
La carpeta "src/main/resources" contiene recursos que no son parte del código de aplicación.
El tema es que si tiramos ahí cualquier cosa, cual si fuera una bolsa de gatos, eventualmente se vuelve un problema encontrar el recurso que buscamos (Ustedes tienen solo un archivo, pero en proyectos grandes, esa carpeta puede tener muchisimos archivos)
Lo ideal es que a esta carpeta le den la misma importancia de organización que le dan a el código, y por tanto, los scripts se encuentren en una carpeta del estilo "src/main/resources/db/scripts" y no sueltos.

**Comment by juanmardefago** [comment]
Agregado en la nueva branch "PosiblesFixes"
