### ISSUE TITLE
No tienen requerimientos expuestos en los servicios

### ISSUE THREAD

**Issue by nnydjesus** [glmaljkovich/aterrizar.com#14]
Asi como en el TP #1 tenían un servicio con los todos los requerimientos (registrar, validar, ingresar, etc), para los siguientes TP's deberían tener lo mismo.

El servicio es el punto de entrada de la funcionalidad que están exponiendo, por ejemplo en este caso, el servicio de vuelos debería exponer la funcionalidad de: reservar un asiento, consultar asientos disponibles, etc.
Podrían tener otro servicio, servicio de búsquedas, que te permita realizar búsquedas, guardar una búsqueda, etc.

**Comment by nnydjesus** [comment]
Todavia no tienen un servicio para las reservas y consultar asientos disponibles.

**Comment by juanmardefago** [comment]
Uh, pense que lo habiamos subido, más tarde lo subo! 

Mil disculpas!

**Comment by juanmardefago** [comment]
Ya esta subido, perdón por las demoras, pensabamos que lo habíamos hecho cuando hicimos todos los otros fixes, y al meternos con el tp de performance nos olvidamos completamente!
