### ISSUE TITLE
El método getHQL de los criterias compuestos se podría mejorar

### ISSUE THREAD

**Issue by nnydjesus** [glmaljkovich/aterrizar.com#16]
Devuelta... podrían utilizar las funciones de las colecciones (tipo smalltaks/haskell) para tener un código mas limpio:

Ustedes tienen esto:

![screen shot 2016-04-25 at 9 11 07 am](https://cloud.githubusercontent.com/assets/1201972/14783441/094e0bd0-0ac6-11e6-837d-37f11a86abb8.png)

Podria quedar asi:

![screen shot 2016-04-25 at 9 10 56 am](https://cloud.githubusercontent.com/assets/1201972/14783454/1653952a-0ac6-11e6-945f-3e9edb9475f5.png)

**Comment by juanmardefago** [comment]
Como veo que siguen abiertos comento, todos los cosméticos ya los corregimos teniendo en cuenta el syntax sugar de xtend
