### ISSUE TITLE
Crear sub-package dentro del package modelo

### ISSUE THREAD

**Issue by nnydjesus** [glmaljkovich/aterrizar.com#20]
Las clases del modelo van creciendo.. y si están todas dentro de un mismo package es un quilombo.
Podrían categorizar las clases y agruparlas dentro de sub-packages.

**Comment by juanmardefago** [comment]
Corregido y probados los test, sigue andando todo perfecto (Al principio fallo y me volvi loco, pero eran los mapings de hibernate que no saltan como error en eclipse por ser strings!).
