### ISSUE TITLE
Armar la lista de filters para la agregación se puede simplificar

### ISSUE THREAD

**Issue by nnydjesus** [glmaljkovich/aterrizar.com#21]
Ahora tienen esto:

![screen shot 2016-06-05 at 1 56 31 pm](https://cloud.githubusercontent.com/assets/1201972/15806933/c23baab0-2b25-11e6-86fb-9fc9ad457e0e.png)

Si se fijan... esta muy atado a la cantidad de visibilidades que tienen... sumado a la cantidad de código repetido...

se podría simplificar asi:

![screen shot 2016-06-05 at 1 58 51 pm](https://cloud.githubusercontent.com/assets/1201972/15806937/cd5d7c7a-2b25-11e6-8030-7898e39d27f9.png)

**Comment by juanmardefago** [comment]
Arreglado en el ultimo commit, no lo hice así porque no estaba seguro de como pasarle el filter para que se arme bien, en mi solucion quedaba más como:

filter.or(visibilities.map[ vis f | f.eq("visibility", toString(vis))])

pero no andaba porque obviamente f no sabía de donde sacarlo, gracias por la info!
