### ISSUE TITLE
No se valida usuarios en el like o dislike

### ISSUE THREAD

**Issue by nnydjesus** [glmaljkovich/aterrizar.com#22]
Ahora están permitiendo que un usuario le pueda dar like/dislike muchas veces a un destino.
Imaginen que es un post de FB.. tiene sentido que un usuario le pueda dar like varias veces a un mismo post? 
Además, si ya le dió like... le puede dar dislike?

**Comment by juanmardefago** [comment]
Arreglado en el ultimo commit con nuevos test para probar que funciona. No se puede dar like o dislike más de una vez pero si se puede cambiar el like por un dislike y viceversa (en lo que implementé recien, me parecía que tenia más sentido).

Saludos
