### ISSUE TITLE
Agregar destino no valida que el usuario haya reservado un asiento en ese destino

### ISSUE THREAD

**Issue by nnydjesus** [glmaljkovich/aterrizar.com#23]

**Comment by juanmardefago** [comment]
Lo estaba intentando corregir, me di cuenta que nuestras reservas no tienen un destino u origen dado que no lo necesitabamos cuando las hicimos, ni tampoco los asientos tienen destino u origen, solo el tramo lo tiene, y como la única manera de saber si tiene una reserva con ese destino es mediante la reserva, que solo tiene al asiento, no podía consultarlo.

Empece a cambiar las cosas para que la reserva tambien tenga origen y destino y al tocar los mappings de hibernate (que, teniendo en cuenta que es agregar 2 property de string, no debería romper nada), empezó a tirar errores de update/delete query en JDBC, Hibernate, y por alguna razón, en el servicio de amigos, lo raro es que los errores del servicio de amigos eran assert errors, y no siempre era el mismo error, ni siquiera salia el error en el mismo test.

Termine borrando todos los cambios y seguia tirando errores raros en el servicio de amigos, así que borre todo mi proyecto y mi repo local. Lo voy a seguir en un rato, pero me llamo mucho la atención que rompiera tantas cosas si solamente agregue 2 property (que además no tocaban nada de foreign keys, osea, no tendría que romper nada)

Saludos!
