### ISSUE TITLE
No esta testeada la funcionalidad de pedir el perfil

### ISSUE THREAD

**Issue by nnydjesus** [glmaljkovich/aterrizar.com#24]
En **DestinationService** tienen el método _getVisibleProfile_, que es que devuelve el perfil del usuario (busca en la cache, si no esta, lo calcula y lo cachea), pero ese método no se usa en ningún lado.
Minimamente debería estar en un test.

**Comment by juanmardefago** [comment]
En realidad, sino mal recuerdo, testeamos todo con el getProfile (Que es al metodo que llama el getVisibleProfile una vez que calcula la visibilidad que tiene que buscar en base a la relacion entre dos usuarios), porque el getVisibleProfile hace solo eso, calcular la relación entre dos usuarios, y en base a eso llamar a getProfile (Que es el que hace todo el trabajo de buscar si esta en cache, si no esta calcular el perfil y agregarlo a cache y sino devolverlo de cache), y usamos el getProfile para los tests porque sino se hacia demasiado heavy el setup para cada test, aunque tendríamos que haber hecho al menos 1 para ver que calcule la relacion de los users bien (es un switch, no creo que falle, pero bueno).

Ahora en un toque lo agrego

**Comment by juanmardefago** [comment]
Listo, ya agregue los 3 tests, igual como dije antes, solo agrega el checkeo de que visibilidad es la que tiene que pedir a getProfile segun que usuarios le haya pasado (dado que es lo unico que hace el getVisibleProfile).

Saludos!
