### ISSUE TITLE
Utilicen Accesors de Xtend también en el servicio

### ISSUE THREAD

**Issue by alanrodas** [glmaljkovich/aterrizar.com#4]
La anotation "Accessors" puede ser usada sobre la clase (generando todos los getters y setters para todos los campos), o puede usarse sobre un campo, generando solo accesors para ese campo.

En UserService, por ejemplo, basta declarar el accesor para el mailSender, en lugar de definirlo con código como hicieron.

**Comment by juanmardefago** [comment]
No estoy seguro de como tendría que ser, creo que así:
...
@Accessors
EnviadorDeMail mailsender
...

en vez de sobre la clase?

De todas maneras, no queríamos agregarle el getter, dado que con el setter ya nos alcanzaba, sería mejor hacerlo de todas formas?

**Comment by alanrodas** [comment]
Si, exactamente así. Además XTend permite definir opciones en la property accessors
i.e.
@Accessors(PUBLIC_GETTER, PROTECTED_SETTER)

Podrían hacer
@Accessors(PUBLIC_SETTER)

y obtendrían solo el setter.
