### ISSUE TITLE
Usar las properties de Xtend como tales

### ISSUE THREAD

**Issue by alanrodas** [glmaljkovich/aterrizar.com#6]
Xtend tiene un feature muy copado.
Si yo tengo una variable de instancia x en un objeto a, y creo los accessors, puedo acceder de la forma tradicional "a.getX()", pero también como "a.x".
Xtend cuando ve "a.x", lo transforma automagicamente a "a.getX()", con lo cual, si bien puede parecerles medio contra-convencional de acuerdo a lo que les enseñaron en objetos 1 y luego en objetos 2, no está mal hacer "a.x".
También, si yo hago un método y lo llamo "getSasa()", puedo usarlo cual si fuera una propiedad del objeto, haciendo "a.sasa". Por ejemplo, en su caso podrían hacer usuario.validationCode

Por qué usar "a.x" por sobre "a.getX()"?? Hay un montón de discusiones acerca de eso en internet, en especial cuando C# incluyó el feature como Auto-Properties.
Yo creo que hay motivos a favor y los enumero:
1) Es más descriptivo, juan.nombre es más descriptivo que juan.getNombre(), y ni hablar de los setters.
2. Es transparente y puede ser optimizado por el compilador. Si yo escribo a.x = "Juan", el compilador puede trabajar a x cual si fuera una variable publica, lo cual tiene un nivel menos de indirección, y por tanto, ejecuta de forma más performante.
3. Si mañana cambio la implementación de x, de forma que deja de ser una priopiedad, y pasa a ser un metodo, o viceversa, el resto del codigo que lo usa es transparente.
Por ejemplo, ustedes usan un codigo de verificacion que se genera on-the-fly en base al nombre del usuario, pero imaginen que quieren cambiar eso y transformarlo en una variable, que se calcula de forma más compleja, y luego se guarda en la base de datos y se recupera de la misma, eso es transparente usando las properties.

Otro día en clase si quieren discutimos más sobre el tema, por lo pronto, les recomiendo seriamente usar esta caracteristica.

**Comment by juanmardefago** [comment]
Por mi parte se me complica mucho acordarme de eso, más sobre todo cuando es tan parecido a tener una variable publica, teniendo en cuenta lo mucho que nos dijeron que las variables deberían ser siempre privadas, y lo mucho que me acostumbre a siempre hacerlo así, pero voy a intentarlo!
