### ISSUE TITLE
Mergear getUser y checkForUser

### ISSUE THREAD

**Issue by alanrodas** [glmaljkovich/aterrizar.com#7]
checkForUser va a la base de datos, y busca por nombre de usuario. Luego de ejecutar el SELECT, devuelve true o false.
getUser por su parte, verifica primero el usuario con checkForUser  (ejecutando un SELECT) y luego ejecuta otro SELECT para traerse exactamente el mismo dato que ya se había traído en el check, pero que se tiro a la basura.

La mayoría de los frameworks y sistemas evitan este doble viaje a la base combinando ambos métodos en un solo getUser. El mismo devuelve un usuario, si existe, o null si no existe.
Si fuera conveniente tener un checkForUser para exponer, este es quien llama a getUser, y luego compara con null para devolver el resultado. Así, no hay un doble viaje a la base.

Esto es importante que lo corrijan.

**Comment by juanmardefago** [comment]
Arreglado en la nueva branch "PosiblesFixes".

Gracias por la idea de retornar null si no existe el usuario, no sabía que se podía hacer!
