### ISSUE TITLE
Usen un unico punto de acceso para los selects

### ISSUE THREAD

**Issue by alanrodas** [glmaljkovich/aterrizar.com#8]
Estas son las consultas que tienen en su repo

SELECT \* FROM usuarios WHERE username=?;
SELECT \* FROM usuarios WHERE username=? AND password=?;
SELECT validationstate FROM usuarios WHERE username=?;

y luego son siempre un return, o bien del usuario, o bien de si algun atributo del usuario cumple alguna propiedad.

Lo ideal es no tener un SELECT para cada cosa, sino tener uno solo, que devuelve el usuario (y construye un usuario del modelo), y luego testeo la propiedad contra los atributos de ese usuario.
El tener multiples selects trae aparejado errores que uno a veces no ve. Por ejemplo, su getUser lanza una bonita UserDoesNotExistsException, si el usuario no existe. Pero isValidated, nunca tiene en cuenta si el usuario existe o no, y si no existe, me va a explotar feo, y no con el UserDoesNotExistsException. Si yo tengo solo getUser como punto de entrada, las excepciones se lanzan como uno esperaría.

**Comment by juanmardefago** [comment]
Creo que esta arreglado en la nueva branch "PosiblesFixes", tendriamos que hacer un release para que la vean? O con arreglarlo para tenerlo así en el proyecto general alcanza?

**Comment by alanrodas** [comment]
La idea es que, si lo tienen en ese branch, mergeen el mismo con master, y que quede arreglado. En la próxima entrega vemos los issues que estaban abiertos y nos aseguramos de que estén corregidos todos. En ese punto los marcamos como closed. Pero la próxima entrega tiene que incluir esos cambios, así que no lo dejen solo en ese branch, sino en el principal.
